fullnameOverride: devops-info-python
nameOverride: ""

replicaCount: 3

image:
  repository: olesianov/devops-info-python
  tag: lab03
  pullPolicy: IfNotPresent

containerPort: 5000

app:
  environment: dev
  logLevel: info

config:
  file:
    enabled: true
    mountPath: /config
    fileName: config.json
  env:
    enabled: true
    appName: devops-info-python
    featureVisitsEnabled: "true"

env:
  - name: PORT
    value: "5000"
  - name: HOST
    value: "0.0.0.0"
  - name: VISITS_FILE
    value: "/data/visits"

extraEnv: []

secrets:
  enabled: true
  username: "student"
  password: "change-me"

serviceAccount:
  create: true
  name: ""

vault:
  enabled: false
  role: "devops-info-python"
  secretPathConfig: "secret/data/myapp/config"
  secretPathExtra: "secret/data/myapp/extra"
  bonusTemplate:
    enabled: false
    injectCommand: ""

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

statefulset:
  enabled: false
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

livenessProbe:
  exec:
    command:
      - python
      - -c
      - import socket,sys;s=socket.socket();s.settimeout(3);r=s.connect_ex(("127.0.0.1",5000));s.close();sys.exit(0 if r==0 else 1)
  initialDelaySeconds: 20
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 10

readinessProbe:
  exec:
    command:
      - python
      - -c
      - import socket,sys;s=socket.socket();s.settimeout(3);r=s.connect_ex(("127.0.0.1",5000));s.close();sys.exit(0 if r==0 else 1)
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 10

hooks:
  preInstall:
    image: busybox:1.36
  postInstall:
    image: busybox:1.36

ingress:
  enabled: false
  className: nginx
  host: local.devops.lab
  tlsSecretName: devops-lab09-tls
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  paths:
    app1: /app1(/|$)(.*)
    app2: /app2(/|$)(.*)
  backendGoService: devops-info-go-service

persistence:
  enabled: true
  size: 100Mi
  storageClass: ""
  mountPath: /data

rollout:
  canary:
    enabled: false
    pauseDuration: 30s
  blueGreen:
    enabled: false
    autoPromotionEnabled: false
    autoPromotionSeconds: 30
    previewReplicaCount: 1
  analysis:
    enabled: false
    interval: 10s
    count: 3
    failureLimit: 1
