{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "common.fullname" .) }}
  labels:
    app: {{ include "common.legacyAppLabel" . }}
    component: api
    {{- include "common.labels" . | nindent 4 }}
{{- end }}

