{{- if .Values.rollout.blueGreen.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-preview
  labels:
    app: {{ include "common.legacyAppLabel" . }}
    component: api
    purpose: preview-traffic
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "common.legacyAppLabel" . }}
{{- end }}
