---
# Variables for bonus app (e.g. Go/Rust/Java) deployment.
app_name: devops-go
docker_image: "{{ dockerhub_username | default('your_username') }}/devops-info-go"
docker_image_tag: lab03
app_port: 8001
app_internal_port: 8080
compose_project_dir: "/opt/{{ app_name }}"
