apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-info-python-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/olesia8novoselova/DevOps-Core-Course.git
    targetRevision: lab-13
    path: k8s/devops-info-python
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
