fullnameOverride: devops-info-go
nameOverride: ""

replicaCount: 2

image:
  repository: olesianov/devops-info-go
  tag: lab03
  pullPolicy: IfNotPresent

containerPort: 8080

app:
  environment: dev
  logLevel: info

env:
  - name: PORT
    value: "8080"
  - name: HOST
    value: "0.0.0.0"

extraEnv: []

secrets:
  enabled: true
  username: "student"
  password: "change-me"

serviceAccount:
  create: true
  name: ""

vault:
  enabled: false
  role: "devops-info-go"
  # Vault KV v2 paths
  secretPathConfig: "secret/data/myapp/config"
  secretPathExtra: "secret/data/myapp/extra"
  bonusTemplate:
    enabled: false
    injectCommand: ""

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 128Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
